sudo: required
services:
    - docker

before_install:
    - docker build -t beingarindam/react-docker -f Dockerfile.dev .

script:
    - docker run beingarindam/react-docker npm run test -- --coverage